### ISSUE TITLE
test: refactor unit test cases and new test scheme

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/objc-sdk#623]
## Origin

https://github.com/leancloud/objc-sdk/issues/614

## Todo

- [x] move all legacy test cases to `LeanCloudObjc` test scheme
- [x] refactor all test cases
- [x] complement unit test case
